---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-zigbee2mqtt
commonLabels:
  app: zigbee2mqtt

resources:
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: zigbee2mqtt
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: zigbee2mqtt
      namespace: zigbee2mqtt
      annotations:
        gethomepage.dev/href: https://zigbee2mqtt.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Home Automation Device Adder
        gethomepage.dev/group: Home Automation
        gethomepage.dev/icon: zigbee2mqtt
        gethomepage.dev/name: Zigbee2MQTT
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
