
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-settings
  namespace: zigbee2mqtt
data:
  configuration.yaml: |
    advanced:
      homeassistant_discovery_topic: homeassistant
      homeassistant_status_topic: homeassistant/status
      last_seen: ISO_8601
      log_level: debug
      log_output:
      - console
      network_key: '!secrets network_key'
    experimental:
      new_api: true
    frontend:
      port: 8080
    homeassistant: true
    mqtt:
      base_topic: zigbee2mqtt
      include_device_information: true
      server: mqtt://mosquitto.mosquitto.svc
    permit_join: false
    serial:
      adapter: deconz
      port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE3019008-if00
