---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-settings
  namespace: zigbee2mqtt
data:
  configuration.yaml: |
    advanced:
      homeassistant_discovery_topic: homeassistant
      homeassistant_status_topic: homeassistant/status
      last_seen: ISO_8601
      log_level: debug
      log_output:
        - console
      network_key: '!secrets network_key'
      pan_id: 0x1a63
      transmit_power: 20
    devices:
      "0xa81710b786140000":
        friendly_name: "Art Lamps"
      "0xa81710b776eb0000":
        friendly_name: "Avengers"
      "0x0ceff6fffee212c7":
        friendly_name: "Chandelier"
      "0xa81710b775fd0000":
        friendly_name: "Coffee Pot"
      "0xa4c138a5359f14ac":
        friendly_name: "CT Bath Button"
      "0x001788010b5dd5af":
        friendly_name: "CT Bath Center"
      "0x3410f4fffee1e0be":
        friendly_name: "CT Bath Fan"
      "0xa4c13828a4d37236":
        friendly_name: "CT Bath Inside Sensor"
      "0x001788010b5cf266":
        friendly_name: "CT Bath Left"
      "0xa4c138c6791ecc0c":
        friendly_name: "CT Bath Outside Sensor"
      "0x0ceff6fffe67cac4":
        friendly_name: "CT Bath Presence Sensor"
      "0x001788010b621bc5":
        friendly_name: "CT Bath Right"
      "0x3410f4fffee14313":
        friendly_name: "CT Bath Light Switch"
      "0xa4c138656370a23c":
        friendly_name: "CT Bedroom Button"
      "0xa81710b7823a0000":
        friendly_name: "CT Bedroom Fan"
      "0x001788010b6c297a":
        friendly_name: "CT Bedroom Lamp"
      "0x001788010bccbc94":
        friendly_name: "CT Bedroom Motion Sensor"
      "0xa81710b782090000":
        friendly_name: "CT Office Fan"
      "0x001788010bb10d20":
        friendly_name: "CT Office Lamp Left"
      "0x001788010bb10027":
        friendly_name: "CT Office Lamp Right"
      "0xa81710b782790000":
        friendly_name: "CT Office Space Heater"
      "0x0017880109042337":
        friendly_name: "Dice Left"
      "0x0017880109023401":
        friendly_name: "Dice Right"
      "0xa4c138b5a6a4eaeb":
        friendly_name: "Guest Bath Button"
      "0x00178801039e0a09":
        friendly_name: "Guest Bath Center"
      "0x0ceff6fffe680989":
        friendly_name: "Guest Bath Fan"
      "0xa4c13827c6490448":
        friendly_name: "Guest Bath Inside Sensor"
      "0x00178801046a3916":
        friendly_name: "Guest Bath Left"
      "0xa4c13823843ec8c8":
        friendly_name: "Guest Bath Outside Sensor"
      "0x28dba7fffe1b3ba8":
        friendly_name: "Guest Bath Presence Sensor"
      "0x00178801042a62cc":
        friendly_name: "Guest Bath Right"
      "0x842712fffe3fcc6a":
        friendly_name: "Guest Bath Light Switch"
      "0x0ceff6fffee17247":
        friendly_name: "Kitchen Lights"
      "0x001788010919610e":
        friendly_name: "Kitchen Motion Sensor"
      "0xa81710b770520000":
        friendly_name: "Kettle"
      "0xa4c1382388000e8d":
        friendly_name: "Living Room Button"
      "0x001788010b61bbc2":
        friendly_name: "Living Room Left Front"
      "0x001788010bb1767d":
        friendly_name: "Living Room Left Rear"
      "0x001788010b6071f9":
        friendly_name: "Living Room Right Front"
      "0x001788010bb1739b":
        friendly_name: "Living Room Right Rear"
      "0xa81710b77aba0000":
        friendly_name: "Rear Speakers"
      "0x0017880102847eee":
        friendly_name: "RT Bedroom Bottom"
      "0x00158d000abd3612":
        friendly_name: "RT Bedroom Button"
      "0x001788010284cdeb":
        friendly_name: "RT Bedroom Top"
      "0x0017880102f06da2":
        friendly_name: "RT Desk Lamp Left"
      "0x0017880102835133":
        friendly_name: "RT Desk Lamp Right"
      "0x00158d000abd3637":
        friendly_name: "RT Office Button"
      "0xa81710b77f620000":
        friendly_name: "RT Office Fan"
      "0x00178801036254ee":
        friendly_name: "RT Office Wall Bottom"
      "0x0017880102f06e6d":
        friendly_name: "RT Office Wall Top"
    experimental:
      new_api: true
    frontend:
      port: 8080
    groups:
      "1":
        friendly_name: "CT Bath"
        devices:
          - "CT Bath Center"
          - "CT Bath Fan"
          - "CT Bath Inside Sensor"
          - "CT Bath Left"
          - "CT Bath Light Switch"
          - "CT Bath Outside Sensor"
          - "CT Bath Presence Sensor"
          - "CT Bath Right"
      "2":
        friendly_name: "CT Bedroom"
        devices:
          - "CT Bedroom Lamp"
          - "CT Bedroom Motion Sensor"
      "3":
        friendly_name: "CT Office"
        devices:
          - "CT Office Fan"
          - "CT Office Lamp Left"
          - "CT Office Lamp Right"
          - "CT Office Space Heater"
      "4":
        friendly_name: "Dining Room"
        devices:
          - "Chandelier"
          - "Dice Left"
          - "Dice Right"
      "5":
        friendly_name: "Guest Bath"
        devices:
          - "Guest Bath Center"
          - "Guest Bath Fan"
          - "Guest Bath Inside Sensor"
          - "Guest Bath Left"
          - "Guest Bath Light Switch"
          - "Guest Bath Outside Sensor"
          - "Guest Bath Presence Sensor"
          - "Guest Bath Right"
      "6":
        friendly_name: "Kitchen"
        devices:
          - "Coffee Pot"
          - "Kitchen Lights"
          - "Kitchen Motion Sensor"
          - "Kettle"
      "7":
        friendly_name: "Living Room"
        devices:
          - "Art Lamps"
          - "Avengers"
          - "Living Room Left Front"
          - "Living Room Left Rear"
          - "Living Room Right Front"
          - "Living Room Right Rear"
          - "Rear Speakers"
      "8":
        friendly_name: "RT Bedroom"
        devices:
          - "RT Bedroom Bottom"
          - "RT Bedroom Button"
          - "RT Bedroom Top"
      "9":
        friendly_name: "RT Office"
        devices:
          - "RT Desk Lamp Left"
          - "RT Desk Lamp Right"
          - "RT Office Button"
          - "RT Office Fan"
          - "RT Office Wall Top"
    homeassistant: true
    mqtt:
      base_topic: zigbee2mqtt
      include_device_information: true
      server: mqtt://mosquitto.mosquitto.svc
    permit_join: false
    serial:
      port: tcp://192.168.1.250:6638
      baudrate: 115200
      disable_led: false
