---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  annotations:
    external-dns.alpha.kubernetes.io/hostname: zigbee2mqtt.crt.house
    external-dns.alpha.kubernetes.io/target: crt.house
    nginx.org/websocket-services: zigbee2mqtt
    
    
spec:
  ingressClassName: nginx-crt-house
  rules:
    - host: "zigbee2mqtt.crt.house"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: zigbee2mqtt
                port:
                  number: 8080
  tls:
    - hosts:
      - zigbee2mqtt.crt.house
      secretName: 
