"0xa81710b786140000":
  friendly_name: "Art Lamps"
"0xa81710b776eb0000":
  friendly_name: "Avengers"
"0x0ceff6fffee212c7":
  friendly_name: "Chandelier"
"0xa81710b775fd0000":
  friendly_name: "Coffee Pot"
"0xa4c138a5359f14ac":
  friendly_name: "CT Bath Button"
"0x001788010b5dd5af":
  friendly_name: "CT Bath Center"
"0xb40ecfd16a700000":
  friendly_name: "CT Bath Dehumidifier"
"0x3410f4fffee1e0be":
  friendly_name: "CT Bath Fan"
"0x001788010b5cf266":
  friendly_name: "CT Bath Left"
"0xa4c138c6791ecc0c":
  friendly_name: "CT Bath Outside Sensor"
"0x0ceff6fffe67cac4":
  friendly_name: "CT Bath Presence Sensor"
"0x001788010b621bc5":
  friendly_name: "CT Bath Right"
"0x3410f4fffee14313":
  friendly_name: "CT Bath Light Switch"
"0xa4c138656370a23c":
  friendly_name: "CT Bedroom Button"
"0xa81710b7823a0000":
  friendly_name: "CT Bedroom Fan"
"0x001788010b6c297a":
  friendly_name: "CT Bedroom Lamp"
"0x001788010bccbc94":
  friendly_name: "CT Bedroom Motion Sensor"
"0xa81710b782090000":
  friendly_name: "CT Office Fan"
"0x001788010bb10d20":
  friendly_name: "CT Office Lamp Left"
"0x001788010bb10027":
  friendly_name: "CT Office Lamp Right"
"0xa4c13828a4d37236":
  friendly_name: "CT Office Sensor"
"0xa81710b782790000":
  friendly_name: "CT Office Space Heater"
"0x0017880109042337":
  friendly_name: "Dice Left"
"0x0017880109023401":
  friendly_name: "Dice Right"
"0xa4c13827c6490448":
  friendly_name: "Dining Room Sensor"
"0xa4c138b5a6a4eaeb":
  friendly_name: "Guest Bath Button"
"0x00178801039e0a09":
  friendly_name: "Guest Bath Center"
"0xb40ecfd12d530000":
  friendly_name: "Guest Bath Dehumidifier"
"0x0ceff6fffe680989":
  friendly_name: "Guest Bath Fan"
"0x00178801046a3916":
  friendly_name: "Guest Bath Left"
"0x28dba7fffe1b3ba8":
  friendly_name: "Guest Bath Presence Sensor"
"0x00178801042a62cc":
  friendly_name: "Guest Bath Right"
"0x842712fffe3fcc6a":
  friendly_name: "Guest Bath Light Switch"
"0x0ceff6fffee17247":
  friendly_name: "Kitchen Lights"
"0x001788010919610e":
  friendly_name: "Kitchen Motion Sensor"
"0xa4c13823843ec8c8":
  friendly_name: "Kitchen Humidity Sensor"
"0xa81710b770520000":
  friendly_name: "Kettle"
"0xa4c1382388000e8d":
  friendly_name: "Living Room Button"
"0x001788010b61bbc2":
  friendly_name: "Living Room Left Front"
"0x001788010bb1767d":
  friendly_name: "Living Room Left Rear"
"0x001788010b6071f9":
  friendly_name: "Living Room Right Front"
"0x001788010bb1739b":
  friendly_name: "Living Room Right Rear"
"0xa81710b77aba0000":
  friendly_name: "Rear Speakers"
"0x0017880102847eee":
  friendly_name: "RT Bedroom Bottom"
"0x00158d000abd3612":
  friendly_name: "RT Bedroom Button"
"0x001788010284cdeb":
  friendly_name: "RT Bedroom Top"
"0x0017880102f06da2":
  friendly_name: "RT Desk Lamp Left"
"0x0017880102835133":
  friendly_name: "RT Desk Lamp Right"
"0x00158d000abd3637":
  friendly_name: "RT Office Button"
"0xa81710b77f620000":
  friendly_name: "RT Office Fan"
"0x00178801036254ee":
  friendly_name: "RT Office Wall Bottom"
"0x0017880102f06e6d":
  friendly_name: "RT Office Wall Top"
